import React from 'react'
import { useState } from 'react';
import Modal from 'react-bootstrap/Modal';
import { FaPencilAlt } from "react-icons/fa";
import { HiCheck } from "react-icons/hi";
import { PiUserRectangleFill } from "react-icons/pi";
import { MdOutlineVerified } from "react-icons/md";
import { AiOutlineQuestionCircle } from "react-icons/ai";
import Form from 'react-bootstrap/Form';
import "./BrandStepperStyle.css"

const SecurityTab = (props) => {
    const [show, setShow] = useState(false);

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);
    return (
        <div>
            <div className='myInfo-tab'>
                <h3 className='mb-0 pb-3'>Password & security</h3>

                <div className="border-[1px] rounded-xl p-6 mb-4 border-[#0055a2]">
                    <div className="flex justify-between items-center">
                        <p className='mb-0 text-2xl font-[500]'>Authentication options</p>

                    </div>
                    <div className="flex justify-between items-center pt-10">
                        <p className='mb-0 text-xl font-[500]'>Password</p>
                        <button onClick={handleShow} className='border-2 border-[#0055a2] rounded-full h-10 w-10 flex items-center justify-center'>
                            <FaPencilAlt className='text-[#0055a2]' />
                        </button>
                    </div>
                    <div className="flex pt-2">
                        <div className="mr-4 mt-[6px] w-5 h-5 rounded-full flex items-center justify-center border-2 border-[#0055a2]">
                            <HiCheck className='text-[18px] text-[#0055a2]' />
                        </div>
                        <div className="">
                            <p className='text-lg mb-0 font-[500]'>Password has been set</p>
                            <p className='text-lg'>Choose a strong, unique password that’s at least 8 characters long.</p>
                        </div>
                    </div>
                </div>
                <div className="border-[1px] rounded-xl py-6 mb-4 border-[#0055a2]">
                    <div className="flex justify-between px-6 items-center">
                        <p className='mb-0 text-xl font-[500]'>Two-step verification options</p>
                        <button onClick={handleShow} className='border-2 border-[#0055a2] rounded-full h-10 w-10 flex items-center justify-center'>
                            <MdOutlineVerified className='text-[#0055a2]' />
                        </button>
                    </div>
                    <p className='text-lg px-6'>Add an extra layer of security to block unauthorized access and protect your account.</p>
                    <div className="flex justify-between items-center pt-10 pb-6 px-6 border-b">
                        <div className="">
                            <h6 className='font-[500] text-lg flex items-center'>Authenticator app code <AiOutlineQuestionCircle className='ml-2 mr-6' /><span className='text-gray-600'>(Recommended)</span></h6>
                            <p className='text-lg'>Enter a code generated by your authenticator app to confirm it’s you.</p>
                        </div>
                        <div className="">
                            <Form>
                                <Form.Check
                                    type="switch"
                                    id="custom-switch"
                                    // label="Check this switch"
                                />
                              
                            </Form>
                        </div>
                    </div>
                    <div className="flex justify-between items-center pt-10 pb-6 px-6 border-b">
                        <div className="">
                            <h6 className='font-[500] text-lg flex items-center'>Mobile app prompt<AiOutlineQuestionCircle className='ml-2 mr-6' /></h6>
                            <p className='text-lg'>Receive a prompt from your mobile app to confirm it’s you.</p>
                        </div>
                        <div className="">
                            <Form>
                                <Form.Check
                                    type="switch"
                                    id="custom-switch"
                                    // label="Check this switch"
                                />
                              
                            </Form>
                        </div>
                    </div>
                    <div className="flex justify-between items-center pt-10 pb-6 px-6 border-b">
                        <div className="">
                            <h6 className='font-[500] text-lg flex items-center'>Text message<AiOutlineQuestionCircle className='ml-2 mr-6' /></h6>
                            <p className='text-lg'>Receive a six digit code by text message to confirm it’s you.</p>
                        </div>
                        <div className="">
                            <Form>
                                <Form.Check
                                    type="switch"
                                    id="custom-switch"
                                    // label="Check this switch"
                                />
                              
                            </Form>
                        </div>
                    </div>
                    <div className="flex justify-between items-center pt-10 pb-6 px-6 border-b">
                        <div className="">
                            <h6 className='font-[500] text-lg flex items-center'>Security question <AiOutlineQuestionCircle className='ml-2 mr-6' /></h6>
                           <div className="">
                            <p className='text-black text-xl'>Not enabled</p>
                           </div>
                            <p className='text-lg'>Answer a question you choose to confirm it’s you.</p>
                        </div>
                        <div className="">
                            <Form>
                                <Form.Check
                                    type="switch"
                                    id="custom-switch"
                                    // label="Check this switch"
                                />
                              
                            </Form>
                        </div>
                    </div>

                </div>
            </div>
            <>
                <Modal
                    show={show}
                    onHide={handleClose}
                    backdrop="static"
                    keyboard={false}
                    {...props}
                    size="lg"
                    aria-labelledby="contained-modal-title-vcenter"
                    centered
                >
                    <Modal.Header closeButton>
                        <Modal.Title>Re-enter password</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                        I will not close if you click outside me. Do not even try to press
                        escape key.
                    </Modal.Body>
                    <Modal.Footer className='border-0'>
                        <button onClick={handleClose} className='text-[#0057a2] font-[500]'>
                            Cancel
                        </button>
                        <button className='border-2 w-fit border-[#0057a2] hover:bg-[#0057a2] hover:text-white transition-all duration-500 ease-in-out text-[#0057a2] py-2 px-4 rounded-full font-bold'>
                            Continue
                        </button>
                    </Modal.Footer>
                </Modal>
            </>
        </div>
    )
}

export default SecurityTab;